### ISSUE TITLE
directaccess.DAQueryException: Non-200 response: 403 Authentication failed

### ISSUE THREAD

**Issue by eliasvitali** [wchatx/direct-access-py#59]
I am getting a 403 Authentication Error partway through a query download. I am confident my API key is correct and I see you have an issue open to implement different handling for throttled request, but I am not getting throttled here it seems. Any insight? 

```
Login successful...
Downloading production data...
Fri, 09 Oct 2020 12:34:45 directaccess INFO     Wrote 100000 records to file /var/cache/analytics/enverus/temp/2020-10-09T12:31:09.364976-producing-entities.csv
Fri, 09 Oct 2020 12:38:29 directaccess INFO     Wrote 200000 records to file /var/cache/analytics/enverus/temp/2020-10-09T12:31:09.364976-producing-entities.csv
Fri, 09 Oct 2020 12:42:24 directaccess INFO     Wrote 300000 records to file /var/cache/analytics/enverus/temp/2020-10-09T12:31:09.364976-producing-entities.csv
Fri, 09 Oct 2020 12:46:19 directaccess INFO     Wrote 400000 records to file /var/cache/analytics/enverus/temp/2020-10-09T12:31:09.364976-producing-entities.csv
Fri, 09 Oct 2020 12:50:04 directaccess INFO     Wrote 500000 records to file /var/cache/analytics/enverus/temp/2020-10-09T12:31:09.364976-producing-entities.csv
Fri, 09 Oct 2020 12:53:40 directaccess INFO     Wrote 600000 records to file /var/cache/analytics/enverus/temp/2020-10-09T12:31:09.364976-producing-entities.csv
Traceback (most recent call last):
  File "enverus_prod.py", line 66, in <module>
    old_csv = get_production_data(env, temp_path)
  File "enverus_prod.py", line 24, in get_production_data
    env.to_csv(producing_entities, os.path.join(temp_path, filename))
  File "/usr/local/lib/python3.6/dist-packages/directaccess/__init__.py", line 87, in to_csv
    for i, row in enumerate(query, start=1):
  File "/usr/local/lib/python3.6/dist-packages/directaccess/__init__.py", line 336, in query
    response.status_code, response.text)
directaccess.DAQueryException: Non-200 response: 403 Authentication failed

```

**Comment by wchatx** [comment]
Thanks for the report @eliasvitali. I agree this doesn't look like invalid credentials or throttling. I'm not aware of any case where a 403 would be returned _after_ successfully getting a token and making some requests against an endpoint.

Can you contact Enverus support and open a case? This would be a problem with the API itself.

**Comment by eliasvitali** [comment]
Ok thank you, I will contact Enverus directly.
